/* Writes target/tables.h: the read-only tables the target solver links in.
 *
 *   pt3/ot3  transition tables, [face][rank]            (default layout)
 *   pt4/ot4  the same tables, [rank][4], fourth slot 0  (O4 layout)
 *   pdbP     permutation pattern database (candidate C)
 *   pdbO     orientation pattern database (candidate B)
 *   src/tw   source[] and twist[] from solver.c, for in-program validation
 *
 * Usage: gen_tables > target/tables.h
 */
#include "model.h"

/* Emits n values as an initializer of rows of `inner` values each (one
 * brace level per row when inner > 0), `line` values per output line.
 */
static void emit(const char *decl, const uint16_t *v, size_t n, size_t inner,
                 size_t line)
{
    printf("%s = {", decl);
    for (size_t i = 0; i < n; ++i) {
        size_t pos = inner ? i % inner : i;
        if (inner && pos == 0)
            printf("%s\n    {", i ? "}," : "");
        printf("%s%s%u", pos ? "," : "", pos % line ? " " : "\n     ", v[i]);
    }
    puts(inner ? "}\n};" : "\n};");
}

static void emit_u8(const char *decl, const uint8_t *v, size_t n, size_t inner,
                    size_t line)
{
    static uint16_t wide[PERMUTATIONS];
    for (size_t i = 0; i < n; ++i)
        wide[i] = v[i];
    emit(decl, wide, n, inner, line);
}

int main(void)
{
    static uint16_t pt4[PERMUTATIONS][4], ot4[ORIENTATIONS][4];
    if (!model_init()) {
        fputs("table construction failed\n", stderr);
        return 1;
    }
    for (int f = 0; f < 3; ++f) {
        for (int x = 0; x < PERMUTATIONS; ++x)
            pt4[x][f] = ptab[f][x];
        for (int x = 0; x < ORIENTATIONS; ++x)
            ot4[x][f] = otab[f][x];
    }
    puts("/* Generated by bench/gen_tables.c from solver.c; do not edit. */");
    puts("#ifndef TARGET_TABLES_H\n#define TARGET_TABLES_H\n");
    puts("#if O4");
    emit("static const uint16_t pt4[5040][4]", &pt4[0][0], 4 * PERMUTATIONS, 4,
         4);
    emit("static const uint16_t ot4[729][4]", &ot4[0][0], 4 * ORIENTATIONS, 4,
         4);
    puts("#else");
    emit("static const uint16_t pt3[3][5040]", &ptab[0][0], 3 * PERMUTATIONS,
         PERMUTATIONS, 16);
    emit("static const uint16_t ot3[3][729]", &otab[0][0], 3 * ORIENTATIONS,
         ORIENTATIONS, 16);
    puts("#endif");
    emit_u8("static const uint8_t pdbP[5040]", pdb_p, PERMUTATIONS, 0, 32);
    emit_u8("static const uint8_t pdbO[729]", pdb_o, ORIENTATIONS, 0, 32);
    emit_u8("static const uint8_t src[3][7]", &source[0][0], 3 * CUBIES, CUBIES,
            7);
    emit_u8("static const uint8_t tw[3][7]", &twist[0][0], 3 * CUBIES, CUBIES,
            7);
    puts("\n#endif");
    return output_failed();
}
